// Export all dashboard components for easier imports
export { default as DashboardLayout } from './DashboardLayout';
export { default as DashboardHeader } from './DashboardHeader';
export { default as Sidebar } from './Sidebar';
export { default as ProductModal } from './ProductModal';
export { default as ProductDetailsModal } from './ProductDetailsModal';
export { default as CustomerDetailsModal } from './CustomerDetailsModal';
export { default as CustomerPasswordModal } from './CustomerPasswordModal';
export { default as StatCard } from './StartCard';
